services:
    typograph:
        class:     TypographBundle\Service\TypographService
        arguments: [ "%typograph.configs%" ]

    twig.extension.typograph:
        class:     TypographBundle\Twig\TypographTwigExtension
        arguments: [ "@typograph" ]
        tags:
            - { name: twig.extension }
